// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Overoom.Infrastructure.Storage.Context;

#nullable disable

namespace Overoom.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Comment.CommentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.ActorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FilmModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmModelId");

                    b.ToTable("FilmActors");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.CdnModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FilmModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmModelId");

                    b.ToTable("FilmCdn");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.CountryModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FilmModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmModelId");

                    b.ToTable("FilmCountries");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.DirectorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FilmModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmModelId");

                    b.ToTable("FilmDirectors");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.FilmModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CountEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountSeasons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UserRating")
                        .HasColumnType("REAL");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.GenreModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FilmModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmModelId");

                    b.ToTable("FilmGenres");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.ScreenWriterModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FilmModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmModelId");

                    b.ToTable("FilmScreenWriters");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.VoiceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CdnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CdnId");

                    b.ToTable("CdnVoices");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.FilmRoom.FilmMessageModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ViewerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("ViewerId");

                    b.ToTable("FilmMessages");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.FilmRoom.FilmRoomModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CdnType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCounter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FilmRooms");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.FilmRoom.FilmViewerModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnPause")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Online")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Series")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimeLine")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("FilmViewers");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Playlist.PlaylistFilmModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlaylistModelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("PlaylistModelId");

                    b.ToTable("PlaylistFilms");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Playlist.PlaylistGenreModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaylistModelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistModelId");

                    b.ToTable("PlaylistGenres");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Playlist.PlaylistModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Rating.RatingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Room.YoutubeRoom.VideoIdModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("VideoIds");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.User.HistoryModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserModelId");

                    b.ToTable("UserHistory");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.User.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.User.WatchlistModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserModelId");

                    b.ToTable("UserWatchlist");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.YoutubeRoom.YoutubeMessageModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ViewerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("ViewerId");

                    b.ToTable("YoutubeMessages");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.YoutubeRoom.YoutubeRoomModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AddAccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCounter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("YoutubeRooms");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.YoutubeRoom.YoutubeViewerModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentVideoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnPause")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Online")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeLine")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("YoutubeViewers");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Comment.CommentModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Overoom.Infrastructure.Storage.Models.User.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Film");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.ActorModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", "FilmModel")
                        .WithMany("Actors")
                        .HasForeignKey("FilmModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmModel");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.CdnModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", null)
                        .WithMany("CdnList")
                        .HasForeignKey("FilmModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.CountryModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", "FilmModel")
                        .WithMany("Countries")
                        .HasForeignKey("FilmModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmModel");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.DirectorModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", "FilmModel")
                        .WithMany("Directors")
                        .HasForeignKey("FilmModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmModel");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.GenreModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", "FilmModel")
                        .WithMany("Genres")
                        .HasForeignKey("FilmModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmModel");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.ScreenWriterModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", "FilmModel")
                        .WithMany("ScreenWriters")
                        .HasForeignKey("FilmModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmModel");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.VoiceModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.CdnModel", "Cdn")
                        .WithMany("Voices")
                        .HasForeignKey("CdnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cdn");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.FilmRoom.FilmMessageModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.FilmRoom.FilmRoomModel", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Overoom.Infrastructure.Storage.Models.FilmRoom.FilmViewerModel", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.FilmRoom.FilmViewerModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.FilmRoom.FilmRoomModel", "Room")
                        .WithMany("Viewers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Playlist.PlaylistFilmModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Overoom.Infrastructure.Storage.Models.Playlist.PlaylistModel", null)
                        .WithMany("Films")
                        .HasForeignKey("PlaylistModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Playlist.PlaylistGenreModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Playlist.PlaylistModel", "PlaylistModel")
                        .WithMany("Genres")
                        .HasForeignKey("PlaylistModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaylistModel");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Rating.RatingModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Overoom.Infrastructure.Storage.Models.User.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Film");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Room.YoutubeRoom.VideoIdModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.YoutubeRoom.YoutubeRoomModel", "Room")
                        .WithMany("VideoIds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.User.HistoryModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Overoom.Infrastructure.Storage.Models.User.UserModel", null)
                        .WithMany("History")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.User.WatchlistModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.Film.FilmModel", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Overoom.Infrastructure.Storage.Models.User.UserModel", null)
                        .WithMany("Watchlist")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.YoutubeRoom.YoutubeMessageModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.YoutubeRoom.YoutubeRoomModel", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Overoom.Infrastructure.Storage.Models.YoutubeRoom.YoutubeViewerModel", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.YoutubeRoom.YoutubeViewerModel", b =>
                {
                    b.HasOne("Overoom.Infrastructure.Storage.Models.YoutubeRoom.YoutubeRoomModel", "Room")
                        .WithMany("Viewers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.CdnModel", b =>
                {
                    b.Navigation("Voices");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Film.FilmModel", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("CdnList");

                    b.Navigation("Countries");

                    b.Navigation("Directors");

                    b.Navigation("Genres");

                    b.Navigation("ScreenWriters");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.FilmRoom.FilmRoomModel", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Viewers");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.Playlist.PlaylistModel", b =>
                {
                    b.Navigation("Films");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.User.UserModel", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("Overoom.Infrastructure.Storage.Models.YoutubeRoom.YoutubeRoomModel", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("VideoIds");

                    b.Navigation("Viewers");
                });
#pragma warning restore 612, 618
        }
    }
}
