// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Room.Infrastructure.Storage.Context;

#nullable disable

namespace Room.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240313185724_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.FilmRooms.FilmRoomModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CdnName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CdnUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSerial")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("FilmRooms");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.FilmRooms.FilmViewerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Beep")
                        .HasColumnType("boolean");

                    b.Property<bool>("Change")
                        .HasColumnType("boolean");

                    b.Property<bool>("FullScreen")
                        .HasColumnType("boolean");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<bool>("Owner")
                        .HasColumnType("boolean");

                    b.Property<bool>("Pause")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Scream")
                        .HasColumnType("boolean");

                    b.Property<int?>("Season")
                        .HasColumnType("integer");

                    b.Property<int?>("Series")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TimeLine")
                        .HasColumnType("interval");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("FilmViewers");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.Messages.MessageModel<Room.Infrastructure.Storage.Models.FilmRooms.FilmRoomModel>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("FilmMessages");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.Messages.MessageModel<Room.Infrastructure.Storage.Models.YoutubeRooms.YoutubeRoomModel>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("YoutubeMessages");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.YoutubeRooms.VideoModel", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Added")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoomId", "VideoId");

                    b.ToTable("YoutubeVideoIds");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.YoutubeRooms.YoutubeRoomModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("VideoAccess")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("YoutubeRooms");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.YoutubeRooms.YoutubeViewerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Beep")
                        .HasColumnType("boolean");

                    b.Property<bool>("Change")
                        .HasColumnType("boolean");

                    b.Property<bool>("FullScreen")
                        .HasColumnType("boolean");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<bool>("Owner")
                        .HasColumnType("boolean");

                    b.Property<bool>("Pause")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Scream")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("TimeLine")
                        .HasColumnType("interval");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("VideoId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("YoutubeViewers");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.FilmRooms.FilmViewerModel", b =>
                {
                    b.HasOne("Room.Infrastructure.Storage.Models.FilmRooms.FilmRoomModel", "Room")
                        .WithMany("Viewers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.Messages.MessageModel<Room.Infrastructure.Storage.Models.FilmRooms.FilmRoomModel>", b =>
                {
                    b.HasOne("Room.Infrastructure.Storage.Models.FilmRooms.FilmRoomModel", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.Messages.MessageModel<Room.Infrastructure.Storage.Models.YoutubeRooms.YoutubeRoomModel>", b =>
                {
                    b.HasOne("Room.Infrastructure.Storage.Models.YoutubeRooms.YoutubeRoomModel", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.YoutubeRooms.VideoModel", b =>
                {
                    b.HasOne("Room.Infrastructure.Storage.Models.YoutubeRooms.YoutubeRoomModel", "Room")
                        .WithMany("Videos")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.YoutubeRooms.YoutubeViewerModel", b =>
                {
                    b.HasOne("Room.Infrastructure.Storage.Models.YoutubeRooms.YoutubeRoomModel", "Room")
                        .WithMany("Viewers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.FilmRooms.FilmRoomModel", b =>
                {
                    b.Navigation("Viewers");
                });

            modelBuilder.Entity("Room.Infrastructure.Storage.Models.YoutubeRooms.YoutubeRoomModel", b =>
                {
                    b.Navigation("Videos");

                    b.Navigation("Viewers");
                });
#pragma warning restore 612, 618
        }
    }
}
